# Configuration file
# https://github.com/connection-lost/LockettePro/wiki/*-config.yml
# If there are missing entries, you can add them manually.

language-file-name: lang_ko.yml
enable-quick-protect: true
enable-uuid-support: false
block-interfere-placement: true
block-item-transfer-in: false
block-item-transfer-out: true
block-hopper-minecart: remove
cache-time-seconds: 0
private-signs:
- '[잠금]'
- '[Private]'
- '[private]'
additional-signs:
- '[추가]'
- '[More Users]'
- '[more users]'
everyone-signs:
- '[모두]'
- '[Everyone]'
- '[everyone]'
timer-signs:
- '[타이머:@]'
- '[Timer:@]'
- '[timer:@]'
lockables:
- OAK_DOOR
- IRON_DOOR
- SPRUCE_DOOR
- BIRCH_DOOR
- JUNGLE_DOOR
- ACACIA_DOOR
- DARK_OAK_DOOR
- OAK_TRAPDOOR
- IRON_TRAPDOOR
- SPRUCE_TRAPDOOR
- BIRCH_TRAPDOOR
- JUNGLE_TRAPDOOR
- ACACIA_TRAPDOOR
- DARK_OAK_TRAPDOOR
- OAK_FENCE_GATE
- SPRUCE_FENCE_GATE
- BIRCH_FENCE_GATE
- JUNGLE_FENCE_GATE
- ACACIA_FENCE_GATE
- DARK_OAK_FENCE_GATE
- CHEST
- TRAPPED_CHEST
- ENDER_CHEST
- DISPENSER
- DROPPER
- FURNACE
- HOPPER
- BREWING_STAND
- IRON_BLOCK
- DIAMOND_BLOCK
- EMERALD_BLOCK
protection-exempt:
- nothing
lock-expire: false
lock-expire-days: 999.9
lock-default-create-time-unix: -1
lock-expire-string: '&c[만료됨]'
